services:
  # NextJS exported app running on an nginx webserver
  my-phonebook-client-prod:
    container_name: my-phonebook-client-prod
    image: weaponsforge/my-phonebook-client:latest
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    networks:
      - my-phonebook-prod
    ports:
      - "3000:3000"

  # Express web server app running in production mode
  my-phonebook-server-prod:
    container_name: my-phonebook-server-prod
    image: weaponsforge/my-phonebook-server:latest
    restart: always
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    networks:
      - my-phonebook-prod
    ports:
      - "3001:3001"

networks:
  my-phonebook-prod:
    name: my-phonebook-prod
    external: false
