version: "3"
services:
  # NextJS exported app running on an nginx webserver
  client-prod:
    container_name: client-prod
    image: weaponsforge/my-phonebook-client:latest
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    networks:
      - my-phonebook-prod
    ports:
      - "3000:3000"

networks:
  my-phonebook-prod:
    name: my-phonebook-prod
    external: false
