name: Lint Files

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  lint-app:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use NodeJS v19.7.0
        uses: actions/setup-node@v3
        with:
          node-version: 19.7.0

      - name: Install Dependencies and Lint
        run: |
          cd client
          npm install
          npm run lint
